import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";
import NextSSRPlugin from "next-ssr-plugin";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
  readonly children: React.ReactNode;
  readonly modal?: React.ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
  const { children, modal } = props;

  return (
    <ClerkProvider>
      <html lang="en">
        <NextSSRPlugin
        /**
         * The `extractRouterConfig` will extract **only** the route configs
         * from the router to prevent additional information from being
         * leaked to the client. The data passed to the client is the same
         * as if you were to fetch `/api/uploadthing` directly.
         */
        />
        <body>
          {children}
          {modal}
        </body>
      </html>
    </ClerkProvider>
  );
}
